### ISSUE TITLE
Missing extension

### ISSUE THREAD

**Issue by StephanEggermont** [activepapers/activepapers-pharo#4]
Extension { #name : #Timespan }

{ #category : #'*ComputationalDocuments' }
Timespan >> asTimespan [
	"Convert from the fixed-size subclasses of Timespan (Month, Week, Year)
	 to generic Timespans that can be used meaningfully in operations such
	 as + or intersection:."
	self class = Timespan
		ifTrue: [ ^ self ]
		ifFalse: [ ^ Timespan starting: self start duration: self duration ]

]

**Comment by StephanEggermont** [comment]
I played with it and I'm not sure more than ^self is needed

**Comment by khinsen** [comment]
Hi Stephan,

first of all, I wonder if you downloaded before or after I added commit 3fc08f0 (which adds the extension to package `ActivePapersExamples`).

As for `^ self`, It's not needed because `self` is the default return value of any method, but I think it's clearer for the reader to put it there explicitly.

**Comment by StephanEggermont** [comment]
I think I forgot to pull
